spring.application.name=licensehub
spring.datasource.url=${LICENSEHUB_DB_URL:jdbc:postgresql://localhost:5433/licensehub}
spring.datasource.username=${LICENSEHUB_DB_USERNAME:licensehub_app}
spring.datasource.password=${LICENSEHUB_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.data.web.pageable.max-page-size=100